# Generated by Django 5.2 on 2025-05-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elder_photos/')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2)),
                ('birth_date', models.DateField()),
                ('id_number', models.CharField(max_length=18, unique=True)),
                ('health_status', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
