# Generated by Django 5.2 on 2025-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='relationship',
            field=models.CharField(choices=[('father-daughter', '父女'), ('mother-daughter', '母女'), ('father-son', '父子'), ('mother-son', '母子'), ('spouse', '配偶'), ('self', '本人'), ('other', '其他')], default='other', max_length=20, verbose_name='亲属关系'),
        ),
    ]
