# Generated by Django 5.2 on 2025-05-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elders', '0002_elder_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='relationship',
            field=models.CharField(choices=[('父女', '父女'), ('母女', '母女'), ('父子', '父子'), ('母子', '母子'), ('配偶', '配偶'), ('本人', '本人'), ('其他', '其他')], default='other', max_length=20, verbose_name='亲属关系'),
        ),
        migrations.AlterField(
            model_name='elder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elders', to=settings.AUTH_USER_MODEL),
        ),
    ]
