# Generated by Django 5.2 on 2025-05-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elders', '0003_alter_elder_relationship_alter_elder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='id_number',
            field=models.CharField(error_messages={'unique': '该身份证号码已存在，请输入其他号码'}, max_length=18, unique=True),
        ),
    ]
