# Generated by Django 5.2.1 on 2025-05-28 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField(verbose_name="周数")),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "周一"),
                            (2, "周二"),
                            (3, "周三"),
                            (4, "周四"),
                            (5, "周五"),
                            (6, "周六"),
                            (7, "周日"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                        ],
                        max_length=20,
                        verbose_name="餐类型",
                    ),
                ),
                ("menu_content", models.TextField(verbose_name="菜单内容")),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "每周菜单",
                "verbose_name_plural": "每周菜单",
                "unique_together": {
                    ("week_number", "day_of_week", "meal_type", "date")
                },
            },
        ),
    ]
