# Generated by Django 5.2.1 on 2025-05-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenu",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="weekly_menus/",
                verbose_name="菜单图片",
            ),
        ),
        migrations.AlterField(
            model_name="weeklymenu",
            name="week_number",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "第1周"),
                    (2, "第2周"),
                    (3, "第3周"),
                    (4, "第4周"),
                    (5, "第5周"),
                    (6, "第6周"),
                    (7, "第7周"),
                    (8, "第8周"),
                    (9, "第9周"),
                    (10, "第10周"),
                    (11, "第11周"),
                    (12, "第12周"),
                    (13, "第13周"),
                    (14, "第14周"),
                    (15, "第15周"),
                    (16, "第16周"),
                    (17, "第17周"),
                    (18, "第18周"),
                    (19, "第19周"),
                    (20, "第20周"),
                    (21, "第21周"),
                    (22, "第22周"),
                    (23, "第23周"),
                    (24, "第24周"),
                    (25, "第25周"),
                    (26, "第26周"),
                    (27, "第27周"),
                    (28, "第28周"),
                    (29, "第29周"),
                    (30, "第30周"),
                    (31, "第31周"),
                    (32, "第32周"),
                    (33, "第33周"),
                    (34, "第34周"),
                    (35, "第35周"),
                    (36, "第36周"),
                    (37, "第37周"),
                    (38, "第38周"),
                    (39, "第39周"),
                    (40, "第40周"),
                    (41, "第41周"),
                    (42, "第42周"),
                    (43, "第43周"),
                    (44, "第44周"),
                    (45, "第45周"),
                    (46, "第46周"),
                    (47, "第47周"),
                    (48, "第48周"),
                    (49, "第49周"),
                    (50, "第50周"),
                    (51, "第51周"),
                    (52, "第52周"),
                ],
                verbose_name="周数",
            ),
        ),
    ]
