# Generated by Django 5.2.1 on 2025-05-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elders", "0004_alter_elder_id_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="拜访日期")),
                ("visit_time", models.TimeField(verbose_name="拜访时间")),
                (
                    "visitor_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="来访人数"
                    ),
                ),
                ("reason", models.TextField(verbose_name="来访事由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("canceled", "已取消"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="二维码标识"
                    ),
                ),
                (
                    "qr_code_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二维码有效期"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="管理员备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "elder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elders.elder",
                        verbose_name="拜访老人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "来访预约",
                "verbose_name_plural": "来访预约",
            },
        ),
    ]
