# Generated by Django 5.2 on 2025-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('relative', 'Relative'), ('staff', 'Staff')], default='relative', max_length=10),
        ),
    ]
