# Generated by Django 5.2.1 on 2025-06-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elders', '0004_alter_elder_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=1)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='入住日期')),
                ('duration_years', models.PositiveIntegerField(default=1, verbose_name='入住年限（年）')),
                ('stay_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkin_date', models.DateField(auto_now_add=True, verbose_name='提交日期')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elders.elder', verbose_name='入住老人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '入住记录',
                'verbose_name_plural': '入住记录',
            },
        ),
    ]
