# Generated by Django 5.2.1 on 2025-06-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
    ]


