# Generated by Django 5.2.1 on 2025-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20250603_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('active', '在住'), ('left', '已退房')], default='active', max_length=10, verbose_name='入住状态'),
        ),
    ]
