# Generated by Django 5.2.1 on 2025-06-04 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_status'),
        ('elders', '0004_alter_elder_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='meal_fee',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='stay_fee',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='total_fee',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveIntegerField()),
                ('stay_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('initial', '首次入住'), ('renew', '续费')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='checkin.checkin')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elders.elder')),
            ],
        ),
    ]
