# Generated by Django 5.2 on 2025-05-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elders', '0004_alter_elder_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, help_text='单位：°C', null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='收缩压，单位：mmHg', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='舒张压，单位：mmHg', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='单位：bpm', null=True)),
                ('blood_sugar', models.FloatField(blank=True, help_text='空腹血糖，单位：mmol/L', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='单位：次/分钟', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='单位：%', null=True)),
                ('weight', models.FloatField(blank=True, help_text='单位：kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='elders.elder')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('elder', 'date')},
            },
        ),
    ]
