# Generated by Django 5.2 on 2025-05-11 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
