# Generated by Django 5.2 on 2025-06-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elders', '0004_alter_elder_id_number'),
        ('health', '0003_healthrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='elders.elder'),
        ),
    ]
